'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Tipo

    '''<summary>
    '''tbl_info control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbl_info As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''btn_procedimiento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_procedimiento As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_instructivo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_instructivo As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_formato control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_formato As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_listado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_listado As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_manual control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_manual As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_registro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_registro As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_norma control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_norma As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_catalogo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_catalogo As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_especificacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_especificacion As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_hoja_calculo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_hoja_calculo As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_volver control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_volver As Global.System.Web.UI.WebControls.LinkButton
End Class
