'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.Runtime.Serialization

<DataContract(IsReference:=True)>
Partial Public Class Documento
    <DataMember()>
    Public Property cod As String
    <DataMember()>
    Public Property nombre As String
    <DataMember()>
    Public Property alcance As String
    <DataMember()>
    Public Property encargado As String
    <DataMember()>
    Public Property creado As Date
    <DataMember()>
    Public Overridable Property Publicacion As ICollection(Of Publicacion) = New HashSet(Of Publicacion)

End Class
