'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Publicacion
    Public Property cod As String
    Public Property documento_version As String
    Public Property detalle As String
    Public Property archivo As Byte()
    Public Property fecha As Date
    Public Property publicado_por As String
    Public Property seccion As String
    Public Property ambito As String
    Public Property sistema_gestion As String
    Public Property procedencia As String
    Public Property tipo_alcance As String

    Public Overridable Property Documento As Documento

End Class
